services:
  web:
    build:
      context: ./django
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/src:/app
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./django
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - ./django/src:/app

  beat:
    build:
      context: ./django
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - ./django/src:/app
