services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/src:/app
    ports:
      - "8000:8000"

  worker:
    volumes:
      - ./django/src:/app

  beat:
    volumes:
      - ./django/src:/app
