# Generated by Django 5.2 on 2026-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.IntegerField(blank=True, choices=[(1, 'Spam'), (2, 'Important'), (3, 'Newsletter'), (4, 'Irrelevant')], null=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
